<<<<<<< HEAD
<<<<<<< HEAD
spring.application.name=backend

spring.datasource.url=jdbc:h2:file:./data/librosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
=======
spring.application.name=demo
=======
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
>>>>>>> 766b250c08777aac5e05593edb69906df4f1a39c

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
<<<<<<< HEAD
spring.h2.console.path=/h2-console
=======
>>>>>>> ac6decbfbee6a4a14a25f88ce76ed3f5a89cfdcb
>>>>>>> 766b250c08777aac5e05593edb69906df4f1a39c
